- name: "Connect to Satellite without a shell script"
  hosts: txd3-confluence.extendhealth.com
  become: True
  vars:
    content_view: RHEL
    product: "Red Hat Enterprise Linux Server"
    repo: "Red Hat Enterprise Linux 7 Server (RPMs)"
    repo_variants:
      - releasever: "7Server"
        basearch: "x86_64"
    organization: "NA-INDIVIDUAL-MARKETPLACE"
    server_url: "ehtx-it-smst002p.int.dir.willis.com"
    
  vars_prompt:
  - name: ansible_user
    prompt: "Enter ansible user which has sudo access"
    private: no
    
  - name: ansible_sudo_pass
    prompt: "Enter sudo password for user"
    private: yes
    
  tasks:
    - name: "Enable {{ repo }} repository"
      katello_repository_set:
        name: "{{ repo }}"
        product: "{{ product }}"
        repositories: "{{ repo_variants }}"
        organization: "{{ org }}"
        state: enabled
    
    - name: "Sync {{ repo }} repository"
      katello_sync:
        repository: "{{ repo }}"
        product: "{{ product }}"
        organization: "{{ org }}"
    
    - name: "Create RHEL ContentView"
      katello_content_view:
        name: "{{ content_view }}"
        repositories:
          - name: "{{ repo }}"
            product: "{{ product }}"
        organization: "{{ org }}"
        state: present
    
    - name: "Publish RHEL content view"
      katello_content_view_version:
        content_view: "{{ content_view }}"
        organization: "{{ org }}"
