---
- name: Create RedHat Subscription
  hosts: wjd1-jiralinux.extendhealth.com
  become: True
  vars:
    ansible_sudo_pass: "{{ ansible_ssh_pass }}"
    
  
  vars_prompt:
    - name: ansible_user
      prompt: "Enter admin username for new server"
      private: no
    
    - name: ansible_ssh_pass
      prompt: "Enter password (for new server)"
      private: yes

    - name: ldap_user
      prompt: "Enter Active Directory user with access to add objects"
      private: no

    - name: ldap_pass
      prompt: "Enter AD user's password"
      private: yes
  
  tasks:
    - name: 'Get CA Certificate'
      yum:
        name: 'http://ehtx-it-smst002p.int.dir.willis.com/pub/katello-ca-consumer-latest.noarch.rpm'
        state: present

    - name: 'Make sure repos are clear'
      command: 'subscription-manager clean'

    - name: 'Register host using subscription_manager'
      community.general.redhat_subscription:
        auto_attach: 'true'
        password: "{{ ldap_pass }}"
        username: "{{ ldap_user }}"
        server_hostname: 'ehtx-it-smst002p.int.dir.willis.com'
        org_id: 'NA-INDIVIDUAL-MARKETPLACE'
        environment: 'preprod/ccv_rh_7_server'
        rhsm_repo_ca_cert: '/etc/rhsm/ca/'

    - name: 'Update through yum'
      yum:
        name: '*'
        state: latest
