---
- hosts: txd3-confluence.extendhealth.com, txd2-confluence.extendhealth.com
  gather_facts: yes
  serial: 1
  tasks:
    - debug: var=ansible_python_interpreter
    - debug: var=ansible_python_version
