---
- name: Get a new server on Satellite
  hosts: txd3-confluence.extendhealth.com
  become: True
  
  vars_prompt:
  - name: ansible_user
    prompt: "Enter ansible user which has sudo access"
    private: no
 
  - name: ansible_ssh_pass
    prompt: "Enter password for ansible user"
    private: yes
    confirm: yes
  
  - name: ansible_sudo_pass
    prompt: "Enter sudo password for user"
    private: yes
    confirm: yes
  
  tasks:
  - name: Copy (curl) bootstrap.py
    ansible.builtin.shell:
      cmd: curl -O http://ehwj-it-smst002p.int.dir.willis.com/pub/bootstrap.py
      
  - name: Make bootstrap.py executable
    ansible.builtin.shell:
      cmd: chmod +x bootstrap.py
      
  - name: Execute bootstrap.py
    ansible.builtin.shell:
      cmd: sudo ./bootstrap.py --login=jacbe --server ehtx-it-smst002p.int.dir.willis.com --location="EHTX - Richardson" --organization="NA-INDIVIDUAL-MARKETPLACE" --hostgroup="EHTX/prod/ccv_rh_7_server" --activationkey=ccv_rh_7_server_prod --download-method https --skip puppet --force
