- hosts: txd3
  become: True
  
  tasks:
  - name: Copy (curl) bootstrap.py
    ansible.builtin.shell:
      cmd: curl -O http://ehwj-it-smst002p.int.dir.willis.com/pub/bootstrap.py
      
  - name: Make bootstrap.py executable
    ansible.builtin.shell:
      cmd: chmod +x bootstrap.py
      
  - name: Execute bootstrap.py
    ansible.builtin.shell:
      cmd: sudo ./bootstrap.py --login=jacbe --server ehtx-it-smst002p.int.dir.willis.com --location="EHTX - Richardson" --organization="NA-INDIVIDUAL-MARKETPLACE" --hostgroup="EHTX/prod/ccv_rh_7_server" --activationkey=ccv_rh_7_server_prod --download-method https --skip puppet --force
